name: CI
on: [push, pull_request]
jobs:

  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep (always pass)
        run: |
          semgrep ci --config p/security-audit --supply-chain --config .semgrep/my-rules.yaml --sarif --output semgrep.sarif
          echo "SEMGREP_EXIT=$?" >> $GITHUB_ENV
        continue-on-error: true
      - name: Show findings in console
        run: |
          echo "=== Semgrep findings ==="
          jq -r '
          .runs[0].results[] as $r |
          .runs[0].tool.driver.rules[] as $rule |
          select($r.ruleId == $rule.id) |
          "-----",
          "Severity: \($rule.defaultConfiguration.level // $r.level)",
          "Rule: \($r.ruleId)",
          "Message: \($r.message.text)",
          "Location: \($r.locations[0].physicalLocation.artifactLocation.uri):\($r.locations[0].physicalLocation.region.startLine)",
          ""
          ' semgrep.sarif

      - name: Fail on ERROR severity
        if: always()
        run: |
            if jq -e '
              .runs[0].results[] as $r |
              .runs[0].tool.driver.rules[] as $rule |
              select($r.ruleId == $rule.id and ($rule.defaultConfiguration.level // $r.level) == "error")
            ' semgrep.sarif > /dev/null; then
              echo "❌ Обнаружены уязвимости уровня ERROR, пайплайн остановлен."
              exit 1
            fi
            echo "✅ Нет находок уровня ERROR."

  codeql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: go
      - uses: github/codeql-action/autobuild@v3
      - uses: github/codeql-action/analyze@v3

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - run: go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.64.4

      - name: Run tests with coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Generate HTML coverage report
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage reports as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports-${{ github.sha }}
          path: |
            coverage.out
            coverage.html
          retention-days: 90
        
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - run: go build -o parser cmd/main.go
